In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = "../dataset/customer_churn_dataset.csv"

## Información de los datos

In [3]:
df = pd.read_csv(data)
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

- **CustomerID:** Código de identificación del cliente
- **Age:** Edad del cliente (en años)
- **Gender:** Género del cliente (Masculino/Femenino)
- **Tenure:** El período de tiempo que el cliente utiliza el servicio (en meses)
- **Usage Frequency:** La frecuencia con la que el cliente utiliza el servicio (en meses)
- **Support Calls:** Frecuencia de llamadas del cliente al servicio de atención
- **Payment Delay:** El período de retraso en el pago de las facturas del servicio por parte de los clientes (en meses)
- **Subscription Type:** El tipo de servicio seleccionado por el cliente (Básico/Estándar/Premium)
- **Contract Length:** El período de contrato del servicio seleccionado por el cliente (Mensual/Trimestral/Anual)
- **Total Spend:** Dinero total gastado por el cliente en el servicio (en USD)
- **Last Interaction:** El período de tiempo desde el último uso del cliente hasta el presente (en meses)
- **Churn:** El estado actual del cliente, continúa con el servicio (0) o lo abandona (1)

## Preprocesamiento de datos

In [4]:
# Permite conocer las dimensiones del DataFrame
df.shape

(64374, 12)

In [5]:
# Para ver la información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [6]:
# Verificar si hay duplicados
df.duplicated().sum()

np.int64(0)

In [7]:
# Verificar si hay datos faltantes
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [8]:
# CustomerID es solo un identificador, no aporta información predictiva
df = df.drop('CustomerID', axis=1)

In [9]:
# Lista de las columnas
df.columns.tolist()

['Age',
 'Gender',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Subscription Type',
 'Contract Length',
 'Total Spend',
 'Last Interaction',
 'Churn']

In [10]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [11]:
# Imprimiendo los valores únicos en todas las columnas menos las numericas.

caracteristicas_numericas = ['Age',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Total Spend',
 'Last Interaction', 
 'Churn']

for col in df.columns:
    if col not in caracteristicas_numericas:
        print(col, df[col].unique())
        print("-" * 70)

Gender ['Female' 'Male']
----------------------------------------------------------------------
Subscription Type ['Basic' 'Standard' 'Premium']
----------------------------------------------------------------------
Contract Length ['Monthly' 'Annual' 'Quarterly']
----------------------------------------------------------------------